//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendScrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendscrip_Meetups
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public string BuyerID { get; set; }
        public string Title { get; set; }
        public System.DateTime StartTime { get; set; }
        public float Price { get; set; }
        public string Location { get; set; }
        public bool Active { get; set; }
    
        public virtual Friendscrip_Accounts Friendscrip_Accounts { get; set; }
        public virtual Friendscrip_Items Friendscrip_Items { get; set; }
    }
}
