//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendScrip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friendscrip_Items
    {
        public Friendscrip_Items()
        {
            this.Friendscrip_Meetups = new HashSet<Friendscrip_Meetups>();
        }
    
        public int ID { get; set; }
        public string AccountID { get; set; }
        public string ItemName { get; set; }
        public string Condition { get; set; }
        public string PickupLocation { get; set; }
        public string MainIntersection { get; set; }
        public string Description { get; set; }
    
        public virtual Friendscrip_Accounts Friendscrip_Accounts { get; set; }
        public virtual ICollection<Friendscrip_Meetups> Friendscrip_Meetups { get; set; }
    }
}
