//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendScrip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScripEntities : DbContext
    {
        public ScripEntities()
            : base("name=ScripEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Friendscrip_Accounts> Friendscrip_Accounts { get; set; }
        public DbSet<Friendscrip_Items> Friendscrip_Items { get; set; }
        public DbSet<Friendscrip_Meetups> Friendscrip_Meetups { get; set; }
    }
}
